#!/bin/bash
# These tests require a running memcached, so set one up.

set -e
set -x

SERVERPORT=$(($RANDOM + 1024))
PIDFILE="$(mktemp -u)"

cleanup() {
	kill $(cat "$PIDFILE")
	rm -f "$PIDFILE"
}

trap cleanup EXIT

memcached -u nobody -d -P "$PIDFILE" -p $SERVERPORT

# Call varnishtest with arguments.
# ($@ would be better, but bash array operations...)
$1 $2 $3 -Dmemcached_port=$SERVERPORT $4
